# Generated by Django 2.2 on 2019-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20190929_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
