# Generated by Django 2.2 on 2019-09-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_movie_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='isdeleted',
            new_name='is_delete',
        ),
    ]
